apiVersion: v1
kind: Pod
metadata:
  name: indexer
  namespace: webhook
  labels:
    name: indexer
spec:
  containers:
  - name: indexer
    image: bmarsh13/kubegaze-indexer:1.0.0
    imagePullPolicy: Always
    env:
      - name: UI_HOST
        value: "http://192.168.1.252:5000"
      - name: TOKEN
        value: ""
      - name: IGNORE_CERT
        value: "yes"
      - name: SLEEP_TIME
        value: "30"


