apiVersion: v1
kind: Pod
metadata:
  name: indexer
  namespace: webhook
  labels:
    name: indexer
spec:
  containers:
  - name: indexer
    image: bmarsh13/kubegaze-indexer:1.0.0
    imagePullPolicy: Always
    env:
      - name: UI_HOST
        value: "https://REPLACE_ME"
      - name: TOKEN
        value: "REPLACE ME"
      - name: IGNORE_CERT
        value: "yes"
      - name: SLEEP_TIME
        value: "30"


